FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./apps/api ./apps/api

RUN pnpm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]